Cell:
      Tcell:
            Treg: {}
            CD4T: {}
            CD8T: {}
            NKT: {}
      Bcell:
            Plasma: {}
      NK: {}
      Dendritic: {}
      Mast: {}
      Neutrophil: {}
      Macrophage: {}
      Monocyte: {}
      Epithelial:
            Goblet: {}
            Paneth: {}
            Enterocyte: {}
            Endocrine: {}
      Endothelial:
            LymphaticEndothelial: {}
            BloodVesselEndothelial: {}
      Fibroblast:
            Myofibroblast: {}
      SmoothMuscle: {}
      Glia: {}
      Neuron: {}
      Tumor: {}
      TransitAmplifying: {}