Beta-catenin: Beta-catenin
CD11b: CD11b
CD11c: CD11c
CD138: CD138
CD16: CD16
CD163: CD163
CD20: CD20
CD209: CD209
CD3: CD3
CD31: CD31
CD4: CD4
CD45: CD45
CD45RO: CD45RO
CD56: CD56
CD63: CD63
CD68: CD68
CD8: CD8
EGFR: EGFR
FoxP3: FoxP3
HLA-Class-2: HLA-Class-2
HLA-Class-1: HLA-Class-1
IDO: IDO
CK17: CK17
CK6: CK6
Ki67: Ki67
LAG3: LAG3
MPO: MPO
OX40: OX40
PDL1: PDL1
PD1: PD1
PanCK: PanCK
SMA: SMA
Vimentin: Vimentin
p53: p53
ADEFENSIN5: DEFA5
ASMA: SMA
BCL2: Bcl-2
CD117: c-kit
CD11C: CD11c
CD123: CD123
CD127: CD127
CD138: CD138
CD15: CD15
CD16: CD16
CD161: CD161
CD163: CD163
CD19: CD19
CD206: CD206
CD21: CD21
CD25: CD25
CD3: CD3
CD31: CD31
CD34: CD34
CD36: CD36
CD38: CD38
CD4: CD4
CD44: CD44
CD45: CD45
CD45RO: CD45RO
CD56: CD56
CD57: CD57
CD66: CD66
CD68: CD68
CD69: CD69
CD7: CD7
CD8: CD8
CD90: CD90
CHGA: CgA
CK7: CK7
COLLAGENIV: Col4
CYTOKERATIN: PanCK
FAP: FAP
HLADR: HLA-Class-2
ITLN1: Intelectin-1
KI67: Ki67
MUC1: MUC1
MUC2: MUC2
NKG2G: NKG2D
OLFM4: OLFM4
PODOPLANIN: PDPN
SOX9: SOX9
SYNAPTOPHYSIN: Synaptophysin
VIMENTIN: Vimentin
