Cell:
      Tcell:
            Treg: {}
            CD4T: {}
            CD8T: {}
            NKT: {}
      Bcell:
            Plasma: {}
      NK: {}
      Dendritic: {}
      Mast: {}
      Neutrophil: {}
      Macrophage: 
            Microglial: {}
            Langerhans: {}
      Monocyte: {}
      Epithelial:
            CollectingDuct: {}
            Melanocyte: {}
            Goblet: {}
            Paneth: {}
            Enterocyte: {}
      Endocrine: 
            AlphaCell: {}
            BetaCell: {}
      Endothelial:
            HSEC: {}
            LymphaticEndothelial: {}
            BloodVesselEndothelial: {}
      Stromal:
            Fibroblast:
                  Stellate: {}
                  Myofibroblast: {}
            SmoothMuscle: {}
            Pericyte: 
                  Mesangial: {}
            CardiacMuscle: {}
      Nerve:
            Neuron: {}
            Glial: {}
      Tumor: {}
      Thrombocyte: {}
      Erythrocyte: {}
      Hepatocyte: {}
      Astrocyte: {}
      EVT: {}
      ICC: {}
      LittoralCell: {}
      Podocyte: {}
# APC: Antigen Presenting Cell, including dendritic cells, macrophages, and B cells, Langerhans
# Leukocyte: Neutrophils, Lymphocytes, Eosinophils, Basophils, Monocytes
# Megakaryocyte: A cell found in the bone marrow. This can include fibroblasts, macrophages, adipocytes, osteoblasts, osteoclasts, endothelial cells and hematopoietic cells.
# Kupffer Cells: In liver, macrohpages are called Kupffer Cells
# CellDeath: Necrotic, Apoptotic (Apototic is tumor, according to the paper, so ignore this part for now)
