Cell:
      Tcell:
            Treg: {}
            CD4T: {}
            CD8T: {}
            NKT: {}
      Bcell:
            Plasma: {}
      NK: {}
      Dendritic: {}
      Mast: {}
      Neutrophil: {}
      Macrophage: 
            Microglial: {}
            Langerhans: {}
      Monocyte: {}
      Epithelial:
            CollectingDuct: {}
            Melanocyte: {}
            Goblet: {}
            Paneth: {}
            Enterocyte: {}
      Endocrine: 
            AlphaCell: {}
            BetaCell: {}
      Endothelial:
            HSEC: {}
            LymphaticEndothelial: {}
            BloodVesselEndothelial: {}
      Stromal:
            Fibroblast:
                  Stellate: {}
                  Myofibroblast: {}
            SmoothMuscle: {}
            Pericyte: 
                  Mesangial: {}
            CardiacMuscle: {}
      Nerve:
            Neuron: {}
            Glial: {}
      Tumor: {}
      Thrombocyte: {}
      Erythrocyte: {}
      Hepatocyte: {}
      Astrocyte: {}
      EVT: {}
      ICC: {}
      LittoralCell: {}
      Podocyte: {}
